//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 12:29:52 PM EEST 
//


package com.mg.mgclient;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FindRecordsResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FindRecordsResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FoundRecords" type="{http://sb.com.ua/webservices/}ArrayOfArrayOfField" minOccurs="0"/&gt;
 *         &lt;element name="ResultTruncated" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Ticket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="EncryptedData" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindRecordsResponse", propOrder = {
    "foundRecords",
    "resultTruncated",
    "ticket",
    "encryptedData"
})
public class FindRecordsResponse {

    @XmlElement(name = "FoundRecords")
    protected ArrayOfArrayOfField foundRecords;
    @XmlElement(name = "ResultTruncated")
    protected boolean resultTruncated;
    @XmlElement(name = "Ticket")
    protected String ticket;
    @XmlElement(name = "EncryptedData")
    protected String encryptedData;

    /**
     * Gets the value of the foundRecords property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfArrayOfField }
     *     
     */
    public ArrayOfArrayOfField getFoundRecords() {
        return foundRecords;
    }

    /**
     * Sets the value of the foundRecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfArrayOfField }
     *     
     */
    public void setFoundRecords(ArrayOfArrayOfField value) {
        this.foundRecords = value;
    }

    /**
     * Gets the value of the resultTruncated property.
     * 
     */
    public boolean isResultTruncated() {
        return resultTruncated;
    }

    /**
     * Sets the value of the resultTruncated property.
     * 
     */
    public void setResultTruncated(boolean value) {
        this.resultTruncated = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicket(String value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the encryptedData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncryptedData() {
        return encryptedData;
    }

    /**
     * Sets the value of the encryptedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncryptedData(String value) {
        this.encryptedData = value;
    }

}
