//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.30 at 12:29:52 PM EEST 
//


package com.mg.mgclient;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mg.mgclient package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mg.mgclient
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionDetailReport }
     * 
     */
    public TransactionDetailReport createTransactionDetailReport() {
        return new TransactionDetailReport();
    }

    /**
     * Create an instance of {@link RequestValues }
     * 
     */
    public RequestValues createRequestValues() {
        return new RequestValues();
    }

    /**
     * Create an instance of {@link TransactionDetailReportResponse }
     * 
     */
    public TransactionDetailReportResponse createTransactionDetailReportResponse() {
        return new TransactionDetailReportResponse();
    }

    /**
     * Create an instance of {@link ArrayOfField }
     * 
     */
    public ArrayOfField createArrayOfField() {
        return new ArrayOfField();
    }

    /**
     * Create an instance of {@link ProfixReport }
     * 
     */
    public ProfixReport createProfixReport() {
        return new ProfixReport();
    }

    /**
     * Create an instance of {@link ProfixReportResponse }
     * 
     */
    public ProfixReportResponse createProfixReportResponse() {
        return new ProfixReportResponse();
    }

    /**
     * Create an instance of {@link GetCityByCountry }
     * 
     */
    public GetCityByCountry createGetCityByCountry() {
        return new GetCityByCountry();
    }

    /**
     * Create an instance of {@link GetCityByCountryResponse }
     * 
     */
    public GetCityByCountryResponse createGetCityByCountryResponse() {
        return new GetCityByCountryResponse();
    }

    /**
     * Create an instance of {@link FindRecordsResponse }
     * 
     */
    public FindRecordsResponse createFindRecordsResponse() {
        return new FindRecordsResponse();
    }

    /**
     * Create an instance of {@link GetCurrencies }
     * 
     */
    public GetCurrencies createGetCurrencies() {
        return new GetCurrencies();
    }

    /**
     * Create an instance of {@link GetCurrenciesResponse }
     * 
     */
    public GetCurrenciesResponse createGetCurrenciesResponse() {
        return new GetCurrenciesResponse();
    }

    /**
     * Create an instance of {@link GetDocumentTypeList }
     * 
     */
    public GetDocumentTypeList createGetDocumentTypeList() {
        return new GetDocumentTypeList();
    }

    /**
     * Create an instance of {@link GetDocumentTypeListResponse }
     * 
     */
    public GetDocumentTypeListResponse createGetDocumentTypeListResponse() {
        return new GetDocumentTypeListResponse();
    }

    /**
     * Create an instance of {@link GetCountries }
     * 
     */
    public GetCountries createGetCountries() {
        return new GetCountries();
    }

    /**
     * Create an instance of {@link GetCountriesResponse }
     * 
     */
    public GetCountriesResponse createGetCountriesResponse() {
        return new GetCountriesResponse();
    }

    /**
     * Create an instance of {@link GetDeliveryOptions }
     * 
     */
    public GetDeliveryOptions createGetDeliveryOptions() {
        return new GetDeliveryOptions();
    }

    /**
     * Create an instance of {@link GetDeliveryOptionsResponse }
     * 
     */
    public GetDeliveryOptionsResponse createGetDeliveryOptionsResponse() {
        return new GetDeliveryOptionsResponse();
    }

    /**
     * Create an instance of {@link GetDirections }
     * 
     */
    public GetDirections createGetDirections() {
        return new GetDirections();
    }

    /**
     * Create an instance of {@link GetDirectionsResponse }
     * 
     */
    public GetDirectionsResponse createGetDirectionsResponse() {
        return new GetDirectionsResponse();
    }

    /**
     * Create an instance of {@link GetStates }
     * 
     */
    public GetStates createGetStates() {
        return new GetStates();
    }

    /**
     * Create an instance of {@link GetStatesResponse }
     * 
     */
    public GetStatesResponse createGetStatesResponse() {
        return new GetStatesResponse();
    }

    /**
     * Create an instance of {@link GetFeatures }
     * 
     */
    public GetFeatures createGetFeatures() {
        return new GetFeatures();
    }

    /**
     * Create an instance of {@link GetFeaturesResponse }
     * 
     */
    public GetFeaturesResponse createGetFeaturesResponse() {
        return new GetFeaturesResponse();
    }

    /**
     * Create an instance of {@link CalcComission }
     * 
     */
    public CalcComission createCalcComission() {
        return new CalcComission();
    }

    /**
     * Create an instance of {@link CalcComissionResponse }
     * 
     */
    public CalcComissionResponse createCalcComissionResponse() {
        return new CalcComissionResponse();
    }

    /**
     * Create an instance of {@link GetTransfer }
     * 
     */
    public GetTransfer createGetTransfer() {
        return new GetTransfer();
    }

    /**
     * Create an instance of {@link GetTransferResponse }
     * 
     */
    public GetTransferResponse createGetTransferResponse() {
        return new GetTransferResponse();
    }

    /**
     * Create an instance of {@link SendRequest }
     * 
     */
    public SendRequest createSendRequest() {
        return new SendRequest();
    }

    /**
     * Create an instance of {@link SendRequestResponse }
     * 
     */
    public SendRequestResponse createSendRequestResponse() {
        return new SendRequestResponse();
    }

    /**
     * Create an instance of {@link SendConfirm }
     * 
     */
    public SendConfirm createSendConfirm() {
        return new SendConfirm();
    }

    /**
     * Create an instance of {@link SendConfirmResponse }
     * 
     */
    public SendConfirmResponse createSendConfirmResponse() {
        return new SendConfirmResponse();
    }

    /**
     * Create an instance of {@link SendCancel }
     * 
     */
    public SendCancel createSendCancel() {
        return new SendCancel();
    }

    /**
     * Create an instance of {@link SendCancelResponse }
     * 
     */
    public SendCancelResponse createSendCancelResponse() {
        return new SendCancelResponse();
    }

    /**
     * Create an instance of {@link SendEdit }
     * 
     */
    public SendEdit createSendEdit() {
        return new SendEdit();
    }

    /**
     * Create an instance of {@link SendEditResponse }
     * 
     */
    public SendEditResponse createSendEditResponse() {
        return new SendEditResponse();
    }

    /**
     * Create an instance of {@link PayoutRequest }
     * 
     */
    public PayoutRequest createPayoutRequest() {
        return new PayoutRequest();
    }

    /**
     * Create an instance of {@link PayoutRequestResponse }
     * 
     */
    public PayoutRequestResponse createPayoutRequestResponse() {
        return new PayoutRequestResponse();
    }

    /**
     * Create an instance of {@link PayoutConfirm }
     * 
     */
    public PayoutConfirm createPayoutConfirm() {
        return new PayoutConfirm();
    }

    /**
     * Create an instance of {@link PayoutConfirmResponse }
     * 
     */
    public PayoutConfirmResponse createPayoutConfirmResponse() {
        return new PayoutConfirmResponse();
    }

    /**
     * Create an instance of {@link PayoutCancel }
     * 
     */
    public PayoutCancel createPayoutCancel() {
        return new PayoutCancel();
    }

    /**
     * Create an instance of {@link PayoutCancelResponse }
     * 
     */
    public PayoutCancelResponse createPayoutCancelResponse() {
        return new PayoutCancelResponse();
    }

    /**
     * Create an instance of {@link ReturnRequest }
     * 
     */
    public ReturnRequest createReturnRequest() {
        return new ReturnRequest();
    }

    /**
     * Create an instance of {@link ReturnRequestResponse }
     * 
     */
    public ReturnRequestResponse createReturnRequestResponse() {
        return new ReturnRequestResponse();
    }

    /**
     * Create an instance of {@link ReturnConfirm }
     * 
     */
    public ReturnConfirm createReturnConfirm() {
        return new ReturnConfirm();
    }

    /**
     * Create an instance of {@link ReturnConfirmResponse }
     * 
     */
    public ReturnConfirmResponse createReturnConfirmResponse() {
        return new ReturnConfirmResponse();
    }

    /**
     * Create an instance of {@link ReturnCancel }
     * 
     */
    public ReturnCancel createReturnCancel() {
        return new ReturnCancel();
    }

    /**
     * Create an instance of {@link ReturnCancelResponse }
     * 
     */
    public ReturnCancelResponse createReturnCancelResponse() {
        return new ReturnCancelResponse();
    }

    /**
     * Create an instance of {@link FindClient }
     * 
     */
    public FindClient createFindClient() {
        return new FindClient();
    }

    /**
     * Create an instance of {@link FindClientResponse }
     * 
     */
    public FindClientResponse createFindClientResponse() {
        return new FindClientResponse();
    }

    /**
     * Create an instance of {@link ConfirmOperation }
     * 
     */
    public ConfirmOperation createConfirmOperation() {
        return new ConfirmOperation();
    }

    /**
     * Create an instance of {@link ConfirmOperationResponse }
     * 
     */
    public ConfirmOperationResponse createConfirmOperationResponse() {
        return new ConfirmOperationResponse();
    }

    /**
     * Create an instance of {@link GetPoints }
     * 
     */
    public GetPoints createGetPoints() {
        return new GetPoints();
    }

    /**
     * Create an instance of {@link GetPointsResponse }
     * 
     */
    public GetPointsResponse createGetPointsResponse() {
        return new GetPointsResponse();
    }

    /**
     * Create an instance of {@link GetPointTree }
     * 
     */
    public GetPointTree createGetPointTree() {
        return new GetPointTree();
    }

    /**
     * Create an instance of {@link GetPointTreeResponse }
     * 
     */
    public GetPointTreeResponse createGetPointTreeResponse() {
        return new GetPointTreeResponse();
    }

    /**
     * Create an instance of {@link OWExecOperation }
     * 
     */
    public OWExecOperation createOWExecOperation() {
        return new OWExecOperation();
    }

    /**
     * Create an instance of {@link OWExecOperationResponse }
     * 
     */
    public OWExecOperationResponse createOWExecOperationResponse() {
        return new OWExecOperationResponse();
    }

    /**
     * Create an instance of {@link HelloWorld }
     * 
     */
    public HelloWorld createHelloWorld() {
        return new HelloWorld();
    }

    /**
     * Create an instance of {@link HelloWorldResponse }
     * 
     */
    public HelloWorldResponse createHelloWorldResponse() {
        return new HelloWorldResponse();
    }

    /**
     * Create an instance of {@link GetFormatInfo }
     * 
     */
    public GetFormatInfo createGetFormatInfo() {
        return new GetFormatInfo();
    }

    /**
     * Create an instance of {@link GetFormatInfoResponse }
     * 
     */
    public GetFormatInfoResponse createGetFormatInfoResponse() {
        return new GetFormatInfoResponse();
    }

    /**
     * Create an instance of {@link FormatInfo }
     * 
     */
    public FormatInfo createFormatInfo() {
        return new FormatInfo();
    }

    /**
     * Create an instance of {@link GetMethodInfo }
     * 
     */
    public GetMethodInfo createGetMethodInfo() {
        return new GetMethodInfo();
    }

    /**
     * Create an instance of {@link GetMethodInfoResponse }
     * 
     */
    public GetMethodInfoResponse createGetMethodInfoResponse() {
        return new GetMethodInfoResponse();
    }

    /**
     * Create an instance of {@link MethodInfo }
     * 
     */
    public MethodInfo createMethodInfo() {
        return new MethodInfo();
    }

    /**
     * Create an instance of {@link ExecOperation }
     * 
     */
    public ExecOperation createExecOperation() {
        return new ExecOperation();
    }

    /**
     * Create an instance of {@link ExecOperationResponse }
     * 
     */
    public ExecOperationResponse createExecOperationResponse() {
        return new ExecOperationResponse();
    }

    /**
     * Create an instance of {@link GetUsersOfPoint }
     * 
     */
    public GetUsersOfPoint createGetUsersOfPoint() {
        return new GetUsersOfPoint();
    }

    /**
     * Create an instance of {@link GetUsersOfPointResponse }
     * 
     */
    public GetUsersOfPointResponse createGetUsersOfPointResponse() {
        return new GetUsersOfPointResponse();
    }

    /**
     * Create an instance of {@link AddUser }
     * 
     */
    public AddUser createAddUser() {
        return new AddUser();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link UpdateUser }
     * 
     */
    public UpdateUser createUpdateUser() {
        return new UpdateUser();
    }

    /**
     * Create an instance of {@link UpdateUserResponse }
     * 
     */
    public UpdateUserResponse createUpdateUserResponse() {
        return new UpdateUserResponse();
    }

    /**
     * Create an instance of {@link ChangePassword }
     * 
     */
    public ChangePassword createChangePassword() {
        return new ChangePassword();
    }

    /**
     * Create an instance of {@link ChangePasswordResponse }
     * 
     */
    public ChangePasswordResponse createChangePasswordResponse() {
        return new ChangePasswordResponse();
    }

    /**
     * Create an instance of {@link AddPointSW }
     * 
     */
    public AddPointSW createAddPointSW() {
        return new AddPointSW();
    }

    /**
     * Create an instance of {@link AddPointSWResponse }
     * 
     */
    public AddPointSWResponse createAddPointSWResponse() {
        return new AddPointSWResponse();
    }

    /**
     * Create an instance of {@link GetPointTreeSW }
     * 
     */
    public GetPointTreeSW createGetPointTreeSW() {
        return new GetPointTreeSW();
    }

    /**
     * Create an instance of {@link GetPointTreeSWResponse }
     * 
     */
    public GetPointTreeSWResponse createGetPointTreeSWResponse() {
        return new GetPointTreeSWResponse();
    }

    /**
     * Create an instance of {@link GetUsersOfPointSW }
     * 
     */
    public GetUsersOfPointSW createGetUsersOfPointSW() {
        return new GetUsersOfPointSW();
    }

    /**
     * Create an instance of {@link GetUsersOfPointSWResponse }
     * 
     */
    public GetUsersOfPointSWResponse createGetUsersOfPointSWResponse() {
        return new GetUsersOfPointSWResponse();
    }

    /**
     * Create an instance of {@link GetUserById }
     * 
     */
    public GetUserById createGetUserById() {
        return new GetUserById();
    }

    /**
     * Create an instance of {@link GetUserByIdResponse }
     * 
     */
    public GetUserByIdResponse createGetUserByIdResponse() {
        return new GetUserByIdResponse();
    }

    /**
     * Create an instance of {@link UnlinkUser }
     * 
     */
    public UnlinkUser createUnlinkUser() {
        return new UnlinkUser();
    }

    /**
     * Create an instance of {@link UnlinkUserResponse }
     * 
     */
    public UnlinkUserResponse createUnlinkUserResponse() {
        return new UnlinkUserResponse();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetOfflineTaskList }
     * 
     */
    public GetOfflineTaskList createGetOfflineTaskList() {
        return new GetOfflineTaskList();
    }

    /**
     * Create an instance of {@link GetOfflineTaskListResponse }
     * 
     */
    public GetOfflineTaskListResponse createGetOfflineTaskListResponse() {
        return new GetOfflineTaskListResponse();
    }

    /**
     * Create an instance of {@link GetOfflineReport }
     * 
     */
    public GetOfflineReport createGetOfflineReport() {
        return new GetOfflineReport();
    }

    /**
     * Create an instance of {@link GetOfflineReportResponse }
     * 
     */
    public GetOfflineReportResponse createGetOfflineReportResponse() {
        return new GetOfflineReportResponse();
    }

    /**
     * Create an instance of {@link CancelOfflineReport }
     * 
     */
    public CancelOfflineReport createCancelOfflineReport() {
        return new CancelOfflineReport();
    }

    /**
     * Create an instance of {@link CancelOfflineReportResponse }
     * 
     */
    public CancelOfflineReportResponse createCancelOfflineReportResponse() {
        return new CancelOfflineReportResponse();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link ArrayOfArrayOfField }
     * 
     */
    public ArrayOfArrayOfField createArrayOfArrayOfField() {
        return new ArrayOfArrayOfField();
    }

    /**
     * Create an instance of {@link ArrayOfFieldInfo }
     * 
     */
    public ArrayOfFieldInfo createArrayOfFieldInfo() {
        return new ArrayOfFieldInfo();
    }

    /**
     * Create an instance of {@link FieldInfo }
     * 
     */
    public FieldInfo createFieldInfo() {
        return new FieldInfo();
    }

    /**
     * Create an instance of {@link ArrayOfEnumeratedValuesInfo }
     * 
     */
    public ArrayOfEnumeratedValuesInfo createArrayOfEnumeratedValuesInfo() {
        return new ArrayOfEnumeratedValuesInfo();
    }

    /**
     * Create an instance of {@link EnumeratedValuesInfo }
     * 
     */
    public EnumeratedValuesInfo createEnumeratedValuesInfo() {
        return new EnumeratedValuesInfo();
    }

}
